input_data_folder: "/home/jovyan/face-recognition-model-development/lfw_dataset/lfw_face_processed.csv"
label_int_mapping_path: "/home/jovyan/face-recognition-model-development/lfw_dataset/lfw_labels_int_mapping.pkl"
output_folder: "/home/jovyan/face-recognition-model-development/train/result/v1.0.0"
input_dim: 512
seed: 1
pretrained: "vggface2"
load_model: "None"
num_workers: 4
lr: 0.005
batch_size: 32
epochs: 60
weight_decay: 0.00001
first_cycle_steps: 15
cycle_mult: 4
max_lr: 0.005
min_lr: 0.00001
warmup_steps: 5
gamma: 0.5